import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import useScrollReveal from "../hooks/useScrollReveal";

const values = ["Integrity", "Excellence", "Service", "Respect", "Innovation", "Teamwork", "Continuous Learning"];

export default function About() {
  useScrollReveal();
  return <><Navbar /><section className="about-hero reveal"><div className="container about-hero-grid"><div className="about-copy"><span className="eyebrow">ABOUT EASY LIFE WELLNESS HUB</span><h1>Empowering people.<br />Transforming lives.</h1><p>Easy Life Wellness Hub is an independent wellness, entrepreneurship and leadership development organization dedicated to improving lives through health education, practical business training and community empowerment.</p></div><div className="about-image-wrap hover-lift easy-about-mark"><span>GOOD HEALTH</span><strong>WEALTH<br />FREEDOM</strong><small>THE EASY LIFE</small></div></div></section><section className="section reveal"><div className="container about-story"><div className="story-card hover-lift"><h2 className="title">Our Vision</h2><p className="muted">To become a leading wellness and entrepreneurship hub where individuals are empowered to live healthier lives, build successful businesses, develop strong leadership skills and create lasting financial independence.</p></div><div className="story-card hover-lift"><h2 className="title">Our Mission</h2><ul className="promise-list"><li>Promote healthy living through wellness education.</li><li>Equip people with practical entrepreneurship skills.</li><li>Raise ethical network-marketing professionals.</li><li>Inspire leadership, personal growth and financial empowerment.</li><li>Build a supportive community with opportunity for everyone.</li></ul></div></div></section><section className="section-alt reveal"><div className="container"><div className="values-header"><span className="eyebrow">OUR CORE VALUES</span><h2 className="title">A community built to grow responsibly.</h2></div><div className="service-grid">{values.map((value) => <div className="service-card hover-lift" key={value}><h3>{value}</h3><p>We put {value.toLowerCase()} into the way we serve members, customers, partners and our wider community.</p></div>)}</div></div></section><Footer /></>;
}
