import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import useScrollReveal from "../hooks/useScrollReveal";

const values = ["Integrity", "Excellence", "Service", "Respect", "Innovation", "Teamwork", "Continuous Learning"];

export default function About() {
  useScrollReveal();
  return <><Navbar /><section className="about-hero reveal"><div className="container about-hero-grid"><div className="about-copy"><span className="eyebrow">ABOUT EASY LIFE WELLNESS HUB</span><h1>Empowering people.<br />Transforming lives.</h1><p>Easy Life Wellness Hub is a naturopathic network marketing platform dedicated to natural health, wellness, and financial freedom. We empower people to live healthy, earn income, and build generational wealth.</p></div><div className="about-image-wrap hover-lift easy-about-mark"><img src="/image-2.png" alt="Easy Life Wellness Hub leadership team" /><div className="easy-about-badge"><span>GOOD HEALTH</span><strong>WEALTH<br />FREEDOM</strong><small>THE EASY LIFE</small></div></div></div></section><section className="section reveal"><div className="container about-story"><div className="story-card hover-lift"><h2 className="title">Our Vision</h2><p className="muted">To help more people build a healthy body, a strong mind, and financial freedom through natural wellness, practical learning, and a supportive community.</p></div><div className="story-card hover-lift"><h2 className="title">Our Mission</h2><ul className="promise-list"><li>Promote healthy living through naturopathic wellness education.</li><li>Provide quality natural products and wellness equipment.</li><li>Equip people with practical entrepreneurship and leadership skills.</li><li>Build ethical network-marketing professionals and mentors.</li><li>Create meaningful outreach and opportunity for everyone.</li></ul></div></div></section><section className="section-alt reveal"><div className="container"><div className="values-header"><span className="eyebrow">OUR CORE VALUES</span><h2 className="title">A community built to grow responsibly.</h2></div><div className="service-grid">{values.map((value) => <div className="service-card hover-lift" key={value}><h3>{value}</h3><p>We put {value.toLowerCase()} into the way we serve members, customers, partners and our wider community.</p></div>)}</div></div></section><Footer /></>;
}
