import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import useScrollReveal from "../hooks/useScrollReveal";

const values = ["Integrity", "Excellence", "Service", "Respect", "Innovation", "Teamwork", "Continuous Learning"];

export default function About() {
  useScrollReveal();
  return <><Navbar /><section className="about-hero reveal"><div className="container about-hero-grid"><div className="about-copy"><span className="eyebrow">ABOUT EASY LIFE WELLNESS HUB</span><h1>Empowering people.<br />Transforming lives.</h1><p>Easy Life Wellness Hub provides wellness products, free practical education, and community support for healthier everyday living.</p></div><div className="about-image-wrap hover-lift easy-about-mark"><img src="/image-2.png" alt="Easy Life Wellness Hub leadership team" /><div className="easy-about-badge"><span>GOOD HEALTH</span><strong>KNOWLEDGE<br />COMMUNITY</strong><small>THE EASY LIFE</small></div></div></div></section><section className="section reveal"><div className="container about-story"><div className="story-card hover-lift"><h2 className="title">Our Vision</h2><p className="muted">To help people build healthier habits and stronger communities through wellness education, practical learning, and support.</p></div><div className="story-card hover-lift"><h2 className="title">Our Mission</h2><ul className="promise-list"><li>Promote healthy living through wellness and hygiene education.</li><li>Provide quality wellness products and equipment.</li><li>Offer free Thursday training at 11:00 AM in Akpakpava.</li><li>Encourage responsible product use according to label directions.</li><li>Support health-awareness outreach and meaningful community impact.</li></ul></div></div></section><section className="section-alt reveal"><div className="container"><div className="values-header"><span className="eyebrow">OUR CORE VALUES</span><h2 className="title">A community built to grow responsibly.</h2></div><div className="service-grid">{values.map((value) => <div className="service-card hover-lift" key={value}><h3>{value}</h3><p>We put {value.toLowerCase()} into the way we serve members, customers, partners and our wider community.</p></div>)}</div></div></section><Footer /></>;
}
