import { useEffect, useState } from "react";
import { createShippingZone, deleteShippingZone, getShippingZones, updateShippingZone } from "../services/api";
import useAuth from "../context/AuthContext";

const blank = { state: "NG", baseDeliveryFee: 0, currency: "NGN", serviceName: "Standard Shipping", handlingTimeMinDays: 1, handlingTimeMaxDays: 2, transitTimeMinDays: 2, transitTimeMaxDays: 7, estimatedDays: "3-9 business days", dutiesAndTaxes: "customer", active: true };

export default function AdminShipping() {
  const { token } = useAuth();
  const [zones, setZones] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [message, setMessage] = useState("");
  const load = () => getShippingZones(token).then(setZones).catch(() => setMessage("Unable to load shipping policies."));
  useEffect(() => { if (token) load(); }, [token]);
  const change = (event) => { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); };
  async function submit(event) { event.preventDefault(); setMessage(""); try { const payload = { ...form, state: form.state.toUpperCase(), baseDeliveryFee: Number(form.baseDeliveryFee), handlingTimeMinDays: Number(form.handlingTimeMinDays), handlingTimeMaxDays: Number(form.handlingTimeMaxDays), transitTimeMinDays: Number(form.transitTimeMinDays), transitTimeMaxDays: Number(form.transitTimeMaxDays), cities: [], categoryPricing: [] }; if (editing) await updateShippingZone(editing, payload, token); else await createShippingZone(payload, token); setForm(blank); setEditing(null); setMessage("Shipping policy saved."); load(); } catch (error) { setMessage(error.message || "Shipping policy could not be saved."); } }
  return <div className="page"><h1>International Shipping Policies</h1><p className="muted">Create one flat, checkout-visible shipping rate per destination country. Use ISO country codes such as NG, GH, GB or US.</p><form className="form" onSubmit={submit}><div className="wizard-grid"><input required name="state" maxLength="2" placeholder="Country code" value={form.state} onChange={change} /><select name="currency" value={form.currency} onChange={change}><option>NGN</option><option>USD</option><option>GBP</option></select><input required type="number" min="0" name="baseDeliveryFee" placeholder="Flat shipping fee" value={form.baseDeliveryFee} onChange={change} /><input required name="serviceName" placeholder="Service name" value={form.serviceName} onChange={change} /></div><div className="wizard-grid"><input type="number" min="0" name="handlingTimeMinDays" placeholder="Min handling days" value={form.handlingTimeMinDays} onChange={change} /><input type="number" min="0" name="handlingTimeMaxDays" placeholder="Max handling days" value={form.handlingTimeMaxDays} onChange={change} /><input type="number" min="0" name="transitTimeMinDays" placeholder="Min transit days" value={form.transitTimeMinDays} onChange={change} /><input type="number" min="0" name="transitTimeMaxDays" placeholder="Max transit days" value={form.transitTimeMaxDays} onChange={change} /></div><input name="estimatedDays" placeholder="Customer-facing delivery estimate" value={form.estimatedDays} onChange={change} /><select name="dutiesAndTaxes" value={form.dutiesAndTaxes} onChange={change}><option value="customer">Customer pays import duties/taxes</option><option value="included">Duties/taxes included</option></select><label><input type="checkbox" name="active" checked={form.active} onChange={change} /> Active</label><button type="submit">{editing ? "Update policy" : "Add policy"}</button>{editing && <button type="button" onClick={() => { setForm(blank); setEditing(null); }}>Cancel</button>}</form>{message && <p>{message}</p>}<div className="grid" style={{ marginTop: 32 }}>{zones.map((zone) => <article className="card" key={zone._id}><h3>{zone.state} · {zone.serviceName}</h3><p>{Number(zone.baseDeliveryFee).toLocaleString()} {zone.currency}</p><p>{zone.handlingTimeMinDays}-{zone.handlingTimeMaxDays} handling days · {zone.transitTimeMinDays}-{zone.transitTimeMaxDays} transit days</p><p>{zone.dutiesAndTaxes === "included" ? "Duties/taxes included" : "Customer pays import duties/taxes"}</p><button onClick={() => { setEditing(zone._id); setForm({ ...blank, ...zone }); }}>Edit</button><button className="btn-danger" onClick={async () => { await deleteShippingZone(zone._id, token); load(); }}>Delete</button></article>)}</div></div>;
}
