import { Link } from "react-router-dom";
import { ArrowRight, BadgeCheck, HeartHandshake, MapPin } from "lucide-react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import useScrollReveal from "../hooks/useScrollReveal";

export default function Director() {
  useScrollReveal();
  return <><Navbar /><main className="director-page">
    <section className="director-hero"><div className="container director-hero-grid">
      <div className="director-hero-copy"><p className="easy-eyebrow">MEET OUR DIRECTOR</p><h1>Dr. Comfort Chinaza<br /><em>Nwaka</em></h1><p className="director-role"><BadgeCheck size={18} aria-hidden="true" /> Licensed Optometrist · Dr. Chizzy</p><p className="director-intro">Director of EASYLIFE WELLNESS HUB, EASYLIFE Clinic, and EASYLIFE Supermarket.</p><p>With a heart for people and a practical approach to wellness, Dr. Comfort Chinaza Nwaka, popularly known as Dr. Chizzy, leads the EASYLIFE family alongside a committed team that makes products, learning, and community support easier to access.</p><div className="easy-actions"><Link className="easy-btn easy-btn-primary" to="/collection">Explore products <ArrowRight size={18} /></Link><Link className="easy-btn easy-btn-outline" to="/contact">Contact EASYLIFE</Link></div></div>
      <div className="director-portrait-card"><span className="director-portrait-label">EASYLIFE LEADERSHIP</span><img src="/ceo.png" alt="Dr. Comfort Chinaza Nwaka (Dr. Chizzy), licensed optometrist and Director of EASYLIFE WELLNESS HUB" /><div className="director-portrait-caption"><strong>Dr. Comfort Chinaza Nwaka</strong><span>Also known as Dr. Chizzy</span></div></div>
    </div></section>
    <section className="section director-story-section reveal"><div className="container director-story"><div><p className="easy-eyebrow">HER STORY</p><h2>Bringing wellness support together in one place.</h2><p>Drawing on her experience with trusted herbal-product companies, Dr. Nwaka established EASYLIFE WELLNESS HUB to make a range of herbal supplements, practical wellness education, and community support easier to find.</p><p>Her work is rooted in helping people build healthier everyday habits, use products according to their directions, and grow through shared learning and encouragement.</p></div><aside className="director-meeting-card content-card"><MapPin size={28} aria-hidden="true" /><p className="easy-eyebrow">MEET THE TEAM</p><h2>Thursday community meetings</h2><p>Join the EASYLIFE team every Thursday by 11:00 AM at 95, Akpakpava, Benin City, Edo State, for wellness education, leadership development, and community connection.</p><Link to="/contact" className="easy-text-link">Ask about the next meeting <ArrowRight size={16} /></Link></aside></div></section>
    <section className="section-alt director-family-section reveal"><div className="container"><div className="easy-section-heading"><p className="easy-eyebrow">THE EASYLIFE FAMILY</p><h2>Connected services, one commitment to care.</h2></div><div className="director-service-grid"><a href="https://clinic.easylifewellnesshub.com" target="_blank" rel="noreferrer" className="content-card"><HeartHandshake size={28} aria-hidden="true" /><h3>EASYLIFE Clinic</h3><p>Explore available eye-care services and appointment information.</p><span>Visit clinic <ArrowRight size={16} /></span></a><a href="https://supermarket.easylifewellnesshub.com" target="_blank" rel="noreferrer" className="content-card"><BadgeCheck size={28} aria-hidden="true" /><h3>EASYLIFE Supermarket</h3><p>Explore everyday household and family essentials.</p><span>Visit supermarket <ArrowRight size={16} /></span></a></div></div></section>
    <section className="section reveal"><div className="container director-records"><p className="easy-eyebrow">REGISTERED BUSINESS</p><h2>EASYLIFE WELLNESS HUB</h2><div className="director-registration-card content-card"><p><strong>Registered business name:</strong> EASYLIFE WELLNESS HUB</p><p><strong>BN registration number:</strong> 9506096</p></div><p>EASYLIFE WELLNESS HUB is registered in Nigeria as a sole proprietorship. For business, product, clinic, supermarket, or partnership enquiries, contact the EASYLIFE team.</p><Link className="easy-btn easy-btn-primary" to="/contact">Contact EASYLIFE</Link></div></section>
  </main><Footer /></>;
}
