import { Link } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import useScrollReveal from "../hooks/useScrollReveal";

export default function Director() {
  useScrollReveal();

  return <><Navbar /><main className="director-page">
    <section className="director-hero reveal"><div className="container director-hero-grid"><div><p className="easy-eyebrow">LEADERSHIP</p><h1>Dr. Chinasa Nwaka</h1><p className="director-role">Director, Easy Life Wellness Hub, Easy Life Clinic &amp; Easy Life Supermarket</p><p>Dr. Chinasa Nwaka leads Easy Life Wellness Hub with a practical commitment to wellness education, responsible product access, and a supportive community. Together with her husband, she is part of the wider Easy Life family of businesses serving people in Edo State and beyond.</p><div className="easy-actions"><Link className="easy-btn easy-btn-primary" to="/collection">Explore wellness products</Link><Link className="easy-btn easy-btn-light" to="/contact">Contact Easy Life</Link></div></div><div className="director-portrait-wrap"><img src="/ceo.png" alt="Dr. Chinasa Nwaka, Director of Easy Life Wellness Hub" /></div></div></section>
    <section className="section reveal"><div className="container director-story"><div><p className="easy-eyebrow">HER STORY</p><h2>Making wellness information and products easier to find.</h2><p>Drawing on her experience working with trusted herbal-product companies, Dr. Nwaka established Easy Life Wellness Hub as an independent place where customers can find a range of herbal supplements alongside practical wellness education and community support.</p><p>Her focus is simple: help people make informed, responsible choices that support healthier everyday living. Products should always be used according to their labels, and customers should seek qualified medical advice for personal health concerns.</p></div><aside className="director-meeting-card content-card"><p className="easy-eyebrow">MEET THE TEAM</p><h2>Thursday community meetings</h2><p>Easy Life and its team meet on Thursdays at 95, Akpakpava, Benin City, Edo State, Nigeria, for wellness education, leadership development, and community connection.</p><Link to="/contact" className="easy-text-link">Ask about the next meeting</Link></aside></div></section>
    <section className="section-alt reveal"><div className="container"><div className="easy-section-heading"><p className="easy-eyebrow">THE EASY LIFE FAMILY</p><h2>Connected services, one commitment to care.</h2></div><div className="director-service-grid"><a href="https://clinic.easylifewellnesshub.com" target="_blank" rel="noreferrer" className="content-card"><h3>Easy Life Clinic</h3><p>Visit the clinic website for available eye-care services and appointment information.</p><span>Visit clinic →</span></a><a href="https://supermarket.easylifewellnesshub.com" target="_blank" rel="noreferrer" className="content-card"><h3>Easy Life Supermarket</h3><p>Visit the supermarket for everyday household and family essentials.</p><span>Visit supermarket →</span></a></div></div></section>
    <section className="section reveal"><div className="container director-records"><p className="easy-eyebrow">REGISTRATION &amp; PROFESSIONAL RECORDS</p><h2>Verification information</h2><p>Easy Life maintains its business-registration and relevant professional-license records. To protect personal details within those records, full documents are shared only for legitimate verification requests.</p><Link className="easy-btn easy-btn-primary" to="/contact">Request verification information</Link></div></section>
  </main><Footer /></>;
}
